version: "3.3"

services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - mongovol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
  netmaker:
    container_name: netmaker
    depends_on:
      - mongodb
    image: gravitl/netmaker:v0.2
    ports:
      - "8081:8081"
      - "50051:50051"
    environment:
      MONGO_HOST: mongodb
    restart: always
  netmaker-ui:
    container_name: netmaker-ui
    depends_on:
      - netmaker
    image: gravitl/netmaker-ui:v0.2
    ports:
      - "80:80"
    environment:
      BACKEND_URL: "http://localhost:8081"
volumes:
  mongovol: {}
