version: "3.4"

services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - /netmaker/mongodb:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
  netmaker:
    privileged: true
    container_name: netmaker
    depends_on:
      - mongodb
    image: gravitl/netmaker:v0.3
    volumes:
      - ./:/local
      - /etc/netclient:/etc/netclient
      - /netmaker/coredns:/root/config/dnsconfig
      - /usr/bin/wg:/usr/bin/wg
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /run/systemd/system:/run/systemd/system
      - /etc/systemd/system:/etc/systemd/system
      - /sys/fs/cgroup:/sys/fs/cgroup
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    network_mode: host
    environment:
      SERVER_GRPC_HOST: "192.168.88.101"
      CLIENT_MODE: "off"
  netmaker-ui:
    container_name: netmaker-ui
    depends_on:
      - netmaker
    image: gravitl/netmaker-ui:v0.3
    links:
      - "netmaker:api"
    ports:
      - "80:80"
    environment:
      BACKEND_URL: "http://64.147.211.252:8081"
