version: "3.4"

volumes:
  dnsconfig:
  driver: local
services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - mongovol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
  netmaker-ui:
    container_name: netmaker-ui
    image: gravitl/netmaker-ui:v0.3
    ports:
      - "80:80"
    environment:
      BACKEND_URL: "http://3.236.111.47:8081"
volumes:
  mongovol: {}
