version: "3.4"

services:
  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:REPLACE_SERVER_IMAGE_TAG
    restart: always
    volumes:
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
    environment:
      BROKER_NAME: "broker.NETMAKER_BASE_DOMAIN"
      BROKER_TYPE: "emqx"
      EMQX_REST_ENDPOINT: "http://mq:18083"
      SERVER_NAME: "NETMAKER_BASE_DOMAIN"
      STUN_DOMAIN: "stun.NETMAKER_BASE_DOMAIN"
      SERVER_HOST: "SERVER_PUBLIC_IP"
      SERVER_API_CONN_STRING: "api.NETMAKER_BASE_DOMAIN:443"
      COREDNS_ADDR: "SERVER_PUBLIC_IP"
      DNS_MODE: "on"
      SERVER_HTTP_HOST: "api.NETMAKER_BASE_DOMAIN"
      API_PORT: "8081"
      MASTER_KEY: "REPLACE_MASTER_KEY"
      CORS_ALLOWED_ORIGIN: "*"
      DISPLAY_KEYS: "on"
      DATABASE: "sqlite"
      NODE_ID: "netmaker-server-1"
      MQ_HOST: "mq"
      MQ_PORT: "443"      
      MQ_SERVER_PORT: "8083"
      STUN_PORT: "3478"      
      VERBOSITY: "1"
      MQ_PASSWORD: "REPLACE_MQ_PASSWORD"
      MQ_USERNAME: "REPLACE_MQ_USERNAME"
    ports:
      - "3478:3478/udp"
  netmaker-ui:
    container_name: netmaker-ui
    image: gravitl/netmaker-ui:REPLACE_UI_IMAGE_TAG
    depends_on:
      - netmaker
      - mq
    links:
      - "netmaker:api"
    restart: always
    environment:
      BACKEND_URL: "https://api.NETMAKER_BASE_DOMAIN"
  caddy:
    image: caddy:2.6.2
    container_name: caddy
    restart: unless-stopped
    volumes:
      - /root/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_conf:/config
    ports:
      - "80:80"
      - "443:443"
  coredns:
    container_name: coredns
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    depends_on:
      - netmaker
    restart: always
    volumes:
      - dnsconfig:/root/dnsconfig
  # mq:
  #   container_name: mq
  #   image: eclipse-mosquitto:2.0.15-openssl
  #   depends_on:
  #     - netmaker
  #   restart: unless-stopped
  #   command: ["/mosquitto/config/wait.sh"]
  #   environment:
  #     MQ_PASSWORD: "REPLACE_MQ_PASSWORD"
  #     MQ_USERNAME: "REPLACE_MQ_USERNAME"
  #   volumes:
  #     - /root/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #     - /root/wait.sh:/mosquitto/config/wait.sh
  #     - mosquitto_logs:/mosquitto/log
  mq:
    container_name: mq
    image: emqx/emqx:5.0.17
    restart: unless-stopped
    environment:
      EMQX_NAME: "emqx"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "REPLACE_MQ_PASSWORD"
      EMQX_DASHBOARD__DEFAULT_USERNAME: "REPLACE_MQ_USERNAME"
    ports:
      - "1883:1883" # MQTT
      - "8883:8883" # SSL MQTT
      - "8083:8083" # Websockets
      - "18083:18083" # Dashboard/REST_API
volumes:
  caddy_data: {}
  caddy_conf: {}
  sqldata: {}
  dnsconfig: {}
  mosquitto_logs: {}
