version: "3.4"

services:
  rqlite:
    container_name: rqlite
    image: rqlite/rqlite
    network_mode: host
    restart: always
    volumes:
      - sqldata:/rqlite/file/data
  netmaker:
    depends_on:
      - rqlite
    privileged: true
    container_name: netmaker
    image: gravitl/netmaker:v0.7
    volumes:
      - ./:/local
      - /etc/netclient:/etc/netclient
      - dnsconfig:/root/config/dnsconfig
      - /usr/bin/wg:/usr/bin/wg
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /run/systemd/system:/run/systemd/system
      - /etc/systemd/system:/etc/systemd/system
      - /sys/fs/cgroup:/sys/fs/cgroup
    cap_add: 
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    network_mode: host
    environment:
      SERVER_HOST: "SERVER_PUBLIC_IP"
      SERVER_API_CONN_STRING: "SERVER_PUBLIC_IP:8081"
      SERVER_GRPC_CONN_STRING: "SERVER_PUBLIC_IP:50051"
      COREDNS_ADDR: "SERVER_PUBLIC_IP"
      GRPC_SSL: "off"
      DNS_MODE: "on"
      SERVER_HTTP_HOST: "SERVER_PUBLIC_IP"
      SERVER_GRPC_HOST: "SERVER_PUBLIC_IP"
      API_PORT: "8081"
      GRPC_PORT: "50051"
      MASTER_KEY: "REPLACE_MASTER_KEY"
      CORS_ALLOWED_ORIGIN: "*"
  netmaker-ui:
    container_name: netmaker-ui
    depends_on:
      - netmaker
    image: gravitl/netmaker-ui:v0.7
    links:
      - "netmaker:api"
    ports:
      - "8082:80"
    environment:
      BACKEND_URL: "https://api.NETMAKER_BASE_DOMAIN"
  coredns:
    depends_on:
      - netmaker 
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    container_name: coredns
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - dnsconfig:/root/dnsconfig
volumes:
  sqldata: {}
  dnsconfig: {}
