server:
  apihost: "" # defaults to 127.0.0.1 or remote ip (SERVER_HOST) if DisableRemoteIPCheck is not set to true. SERVER_API_HOST if set
  apiport: "" # defaults to 8081 or HTTP_PORT (if set)
  grpchost: "" # defaults to 127.0.0.1 or remote ip (SERVER_HOST) if DisableRemoteIPCheck is not set to true. SERVER_GRPC_HOST if set.
  grpcport: "" # defaults to 50051 or GRPC_PORT (if set)
  masterkey: "" # defaults to 'secretkey' or MASTER_KEY (if set)
  allowedorigin: "" # defaults to '*' or CORS_ALLOWED_ORIGIN (if set)
  restbackend: "" # defaults to "on" or REST_BACKEND (if set)
  agentbackend: "" # defaults to "on" or AGENT_BACKEND (if set)
  clientmode: "" # defaults to "on" or CLIENT_MODE (if set)
  dnsmode: "" # defaults to "on" or DNS_MODE (if set)
  disableremoteipcheck: "" # defaults to "false" or DISABLE_REMOTE_IP_CHECK (if set)
mongoconn:
  user: "" # defaults to "mongoadmin" or MONGO_ADMIN (if set)
  pass: "" # defaults to "mongopass" or MONGO_PASS (if set)
  host: "" # defaults to 127.0.0.1 or MONGO_HOST (if set)
  port: "" # defaults to 27017 or MONGO_PORT (if set)
  opts: '' # defaults to '/?authSource=admin' or MONGO_OPTS (if set)
wg:
  keyrequired: "" # defaults to "". If set to "yes", a key is required for signing up for the comms network 
  grpcwg: "" # defaults to "on" or SERVER_GRPC_WIREGUARD if set
  grpciface: "" # defaults to nm-grpc-wg or SERVER_GRPC_WG_INTERFACE if set
  grpcaddr: "" # defaults to 10.101.0.1 or SERVER_GRPC_WG_ADDRESS if set
  grpcaddrrange: "" # defaults to 10.101.0.0/16 or SERVER_GRPC_WG_ADDRESS_RANGE if set
  grpcendpoint: "" # defaults to SERVER_HOST if unset
  grpcport: "" # defaults to 50555 or SERVER_GRPC_WG_PORT if set
  pubkey: "" # defaults to generated value or SERVER_GRPC_WG_PUBKEY if set
  privkey: "" # defaults to generated value or SERVER_GRPC_WG_PRIVKEY if set
