server:
  host: "localhost"
  apiport: "8081"
  grpcport: "50051"
  masterkey: "secretkey"
  allowedorigin: "*"
  restbackend: true            
  agentbackend: true
  defaultnetname: "default"
  defaultnetrange: "10.10.10.0/24"
  createdefault: true
mongoconn:
  user: "mongoadmin"
  pass: "mongopass"
  host: "localhost"
  port: "27017"
  opts: '/?authSource=admin'
