name: Publish Docker test tag

on:
    push:
        branches:
            - 'testing'
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and Push test
              uses: docker/build-push-action@v2
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: ghcr.io/gravitl/netmaker:testing
            - name: Deploy Testing Server and Client(s)
              run: |
                  curl -X POST https://api.github.com/mattkasun/terraform-test/dispatches \
                  -H 'Accept: application/vnd.github.everest-preview+json' \
                  -u ${{ secrets.ACCESS_TOKEN }} 

