name: Publish Docker

    pull_request:
        branches:
            - 'develop'
            - 'master'
    docker:
        runs-on: ubuntu-latest
        steps:
            -
                uses: FranzDiebold/github-env-vars-action@v2
                name: Set Environment Variables
                run: |
                    echo "BUILD_VER=v0.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
                    if [ ${{ CI_HED_REF }} = "master" ]
                    then
                        echo "TAG=latest" >>$GITHUB_ENV
                    else
                        echo "TAG=$CI_HEAD_REF" >> $GITHUB_ENV
                    done
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                context: .
                platforms: linux/amd64, linux/arm64
                push: false
                tags: |
                    nusak/netmaker:${{ env.TAG }}

