name: Integration Test

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      rqlite:
        image: rqlite/rqlite
        ports:
            - 4001:4001
            - 4002:4002
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run tests
        run: |
            go test -p 1 ./... -v
