name: UpgradeRelease

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:

  build-packages:
    uses: ./github/workflows/packages.yml
    with:
      version: ${{ github.event.inputs.version }}

  pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: create pr
        run: |
          curl \
  -X POST \
  -H 'Accept: application/vnd.github+json' \
  -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'\
  -H 'X-GitHub-Api-Version: 2022-11-28' \
  https://api.github.com/repos/${{ github.repository }}/pulls \
  -d '{"title":"{{ github.event.inputs.version }}","head":"release_${{ github.event.inputs.version }}","base":"master"}'


